# Generated by Django 5.1.6 on 2025-02-09 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori İsmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kategori Açıklaması')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Ürün İsmi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('room_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Oda Sayısı')),
                ('bathroom_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Banyo Sayısı')),
                ('floor_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kat Sayısı')),
                ('square_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metrekare')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Resim')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
